# Generated by Django 3.2.16 on 2023-09-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servises', '0002_subscriptions_discount_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='discount_person',
            new_name='price',
        ),
    ]
